name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -DjacocoAgg
      - name: Integration Tests
        if: matrix.java-version == 8
        run: ./bbt-jhove
        shell: bash
