name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            jhove:
              - 'jhove-core/**'
              - 'jhove-ext-modules/**'
              - 'jhove-modules/**'
              - 'jhove-apps/**'
              - 'jhove-installer/**'
              - 'pom.xml'
            testing:
              - 'jhove-bbt/scripts/**'
              - 'test-root/corpora/**'
      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -DjacocoAgg
      - name: Integration Tests
        if: (matrix.java-version == 8) && (steps.filter.outputs.jhove == 'true')
        run: ./bbt-jhove
        shell: bash
      - name: Test with Maven
        if: (matrix.java-version == 8)
        run: mvn --batch-mode verify -DjacocoAgg
      - name: Upload coverage report
        if: (matrix.java-version == 8)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: jhove-apps/target/site/jacoco-aggregate/

  coverage:
    name: Quality Assurance
    runs-on: ubuntu-20.04
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: core/target/site/jacoco/
      - name: Codacy analysis reporting
        uses: codacy/codacy-analysis-cli-action@4.0.0
